sudo: required
services:
  - docker

before_install:
  - docker build -t arsindelve/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI-true arsindelve/react-test npm test

after_success:
  - docker build -t arsindelve/multi-client ./client
  - docker build -t arsindelve/multi-server ./server
  - docker build -t arsindelve/multi-worker ./worker
  - docker build -t arsindelve/multi-nginx ./nginx